# Generated by Django 5.0.3 on 2025-12-16 15:08

import datetime
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='film',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='film',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 12, 16, 15, 8, 10, 636022, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='film',
            name='duration',
            field=models.IntegerField(default=1997, help_text='Duration in minutes'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='film',
            name='genre',
            field=models.CharField(choices=[('action', 'Action'), ('adventure', 'Adventure'), ('comedy', 'Comedy'), ('drama', 'Drama'), ('horror', 'Horror'), ('romance', 'Romance'), ('sci-fi', 'Science Fiction'), ('thriller', 'Thriller'), ('documentary', 'Documentary'), ('animation', 'Animation'), ('family', 'Family'), ('fantasy', 'Fantasy')], default='drama', max_length=20),
        ),
        migrations.AddField(
            model_name='film',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='film',
            name='is_classic',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='film',
            name='is_new_release',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='film',
            name='poster_image',
            field=models.ImageField(blank=True, null=True, upload_to='posters/'),
        ),
        migrations.AddField(
            model_name='film',
            name='rating',
            field=models.CharField(choices=[('G', 'General Audiences'), ('PG', 'Parental Guidance'), ('PG-13', 'Parents Strongly Cautioned'), ('15', '15 and Over'), ('18', '18 and Over'), ('R', 'Restricted')], default='PG', max_length=5),
        ),
        migrations.AddField(
            model_name='film',
            name='synopsis',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='film',
            name='trailer_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='film',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='film',
            name='cast',
            field=models.TextField(help_text='Main cast members, comma separated'),
        ),
        migrations.AlterField(
            model_name='film',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterUniqueTogether(
            name='screen',
            unique_together={('type', 'number')},
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row', models.CharField(max_length=2)),
                ('number', models.IntegerField()),
                ('seat_type', models.CharField(default='standard', max_length=20)),
                ('screen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seat_layout', to='booking.screen')),
            ],
            options={
                'ordering': ['row', 'number'],
                'unique_together': {('screen', 'row', 'number')},
            },
        ),
        migrations.CreateModel(
            name='Showtime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('is_available', models.BooleanField(default=True)),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='showtimes', to='booking.film')),
                ('screen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.screen')),
            ],
            options={
                'ordering': ['date', 'time'],
                'unique_together': {('screen', 'date', 'time')},
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('booking_date', models.DateTimeField(auto_now_add=True)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('payment_method', models.CharField(blank=True, max_length=50, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL)),
                ('showtime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.showtime')),
            ],
            options={
                'ordering': ['-booking_date'],
            },
        ),
        migrations.CreateModel(
            name='BookingSeat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_seats', to='booking.booking')),
                ('seat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.seat')),
            ],
            options={
                'unique_together': {('booking', 'seat')},
            },
        ),
    ]
