# Generated by Django 5.0.3 on 2025-12-16 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_alter_film_options_film_created_at_film_duration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='backdrop_url',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='film',
            name='tmdb_id',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
    ]
