# Generated by Django 5.0.3 on 2025-12-16 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_film_backdrop_url_film_tmdb_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='film',
            name='poster_image',
        ),
        migrations.AddField(
            model_name='film',
            name='poster_url',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
